version: "3.8"

services:
  # Your Go app
  goth-todo:
    build: .
    ports:
      - "8080:8080"
    environment:
      # These environment variables will be accessible in your Go code.
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=goth-todo
    depends_on:
      - postgres

  # Postgres service
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=psql
      - POSTGRES_DB=goth_todo
    ports:
    - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
